dist: bionic
language: java
jdk: openjdk13
services:
    - docker
    - docker-compose
env:
    - COMPOSE_FILE=docker-compose.yml:docker-compose.override.travis.yml
script:
    - ./mvnw clean
    - ./mvnw dependency:resolve dependency:resolve-plugins dependency:sources -DskipTests=true -B -V
    - ./mvnw dependency:tree
    - ./mvnw docker-compose:up
    - ./mvnw clean package site -DskipTests=true -B -V
    - ./mvnw docker-compose:down
