set PORT=5000
set JAVA_OPTS='-Xmx300m -Xss512k -XX:CICompilerCount=2'
set BLOODMONEY_DEV_TESTING=false
set BLOODMONEY_USER_EMAIL=thomas.woehlke@gmail.com
set BLOODMONEY_USER_FULLNAME='Thomas Woehlke'
set BLOODMONEY_USER_PASSWORD="\$2a\$10\$E4HaZIIzdI8PVta3aAR96OlG.4/CL9ww/LJ19iOQiF6QIpOD4mYii"
