#!/usr/bin/env bash

export PORT=5000
export JAVA_OPTS='-Xmx300m -Xss512k -XX:CICompilerCount=2'
export BLOODMONEY_DEV_TESTING=false
export BLOODMONEY_USER_EMAIL='thomas.woehlke@gmail.com'
export BLOODMONEY_USER_FULLNAME='Thomas Woehlke'
export BLOODMONEY_USER_INTERATIONS=4096
export BLOODMONEY_USER_HASH_WIDTH=256
export BLOODMONEY_USER_SECRET=25D8484AB208F08C59FFAFE57DB9FF87
export BLOODMONEY_USER_PASSWORD=gdEB4vO/E8ArK1X1Cj2bnKGDPiJPUusEJfxxzpgUsf4G2fIrz+bHoQ==
export BLOODMONEY_HIBERNATE_DDL_AUTO=create-drop
