# Use postgres/example user/password credentials
version: '3.3'

services:

    db:
        image: postgres:11.5
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: java4postgrespwd
            POSTGRES_USER: java4postgres
            POSTGRES_DB: bloodmoney

    adminer:
        image: adminer:4.7.4
        restart: always
        ports:
            - 8080:8080