endpoints:
    endpoints:
        shutdown:
            enabled: false
server:
    port: ${PORT}
    error:
        path: /fehler
    compression:
        enabled: true
        min-response-size: 2048
spring:
    devtools:
        livereload:
            enabled: true
    application:
        admin:
            enabled: true
    jpa:
        show-sql: true
        open-in-view: true
        generate-ddl: true
        hibernate:
            ddl-auto:  create-drop
            #ddl-auto: update
    thymeleaf:
        cache: false
    session:
        store-type: jdbc
        jdbc:
            initialize-schema: ALWAYS
            cleanup-cron: 0 * * * *simpleworklist *
            #schema: classpath:/org/springframework/session/jdbc/schema-h2.sql
            #table-name: SPRING_SESSION
    main:
        allow-bean-definition-overriding: true
org:
    woehlke:
        bloodmoney:
            dev-testing: ${BLOODMONEY_DEV_TESTING}
            user-config:
                userEmail: ${BLOODMONEY_USER_EMAIL}
                userPassword: ${BLOODMONEY_USER_PASSWORD}
                userFullname: ${BLOODMONEY_USER_FULLNAME}
            web-config:
                export-filename: "measurements.csv"
                export-filename-separator: ";"
                web-add-resource-handlers-static:
                    - "css/"
                    - "img/"
                    - "js/"
                    - "favicon.ico"
                web-add-resource-handlers:
                    - "webjars/"
                    - "h2/"
            web-security:
                iterations: ${BLOODMONEY_USER_INTERATIONS}
                hashWidth: ${BLOODMONEY_USER_HASH_WIDTH}
                secret: ${BLOODMONEY_USER_SECRET}
                login-processing-url: "/j_spring_security_check"
                failure-forward-url: "/login?login_error=1"
                default-success-url: "/"
                login-page: "/login"
                logout-url: "/logout"
                username-parameter: "userEmail"
                password-parameter: "userPassword"
                delete-cookies: "JSESSIONID"
                invalidate-http-session: true
                ant-matchers-fully-authenticated: "/**"
                ant-matchers-permit-all:
                    - "/webjars/**"
                    - "/css/**"
                    - "/img/**"
                    - "/js/**"
                    - "/favicon.ico"
                    - "/test*/**"
                    - "/login*"
                    - "/register*"
                    - "/confirm*/**"
                    - "/resetPassword*"
                    - "/passwordResetConfirm*/**"
                    - "/error*"
                    - "/fehler*"
                    - "/h2*/**"
---
spring:
    profiles: default
    datasource:
        platform: H2
        driver-class-name: org.h2.Driver
        username: sa
        password:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        initialization-mode: embedded
        #temporary data storage
        #url: jdbc:h2:file:/data/sample
        #url: jdbc:h2:file:C:/data/sample (Windows only)
    jta:
        atomikos:
            connectionfactory:
                xa-connection-factory-class-name: org.h2.Driver
    jpa:
        show-sql: true
        database-platform: H2
        hibernate:
            ddl-auto: create-drop
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                temp:
                    use_jdbc_metadata_defaults: false
                naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            #generate_statistics: true
    session:
        store-type: jdbc
        jdbc:
            initialize-schema: embedded
    h2:
        console:
            enabled: true
            settings:
                trace: true
                web-allow-others: true
logging:
    file:
        name: bloodmoney.log
    level:
        root: WARN
        javax: INFO
        com:
            atomikos: WARN
        org:
            thymeleaf:
                dialect:
                    springdata: WARN
            apache:
                commons:
                    logging: WARN
            h2: DEBUG
            springframework:
                data:
                    jdbc: INFO
                    jpa: INFO
                    relational: INFO
                security:
                    web: INFO
                    context: INFO
                boot: WARN
                beans: WARN
                jdbc: WARN
                orm: WARN
                session: WARN
                test: WARN
                mock: WARN
                transaction: WARN
                jca: WARN
                web: WARN
                remoting: WARN
                http: WARN
                expression: WARN
                util: WARN
                lang: WARN
                core: WARN
                cglib: WARN
            hibernate:
                sql: INFO
                query: INFO
                mapping: INFO
                jpa: INFO
                id: INFO
                graph: INFO
                cfg: INFO
                service: INFO
                result: INFO
            ch:
                qos: INFO
            woehlke:
                bloodmoney:
                    config: DEBUG
                    frontend:
                        api: DEBUG
                        config: DEBUG
                        controller: DEBUG
                        model: DEBUG
                    oodm:
                        entities: DEBUG
                        repositories: DEBUG
                        services:
                            impl: DEBUG
                    user:
                        config: DEBUG
                        controller: DEBUG
                        model: DEBUG
                        services:
                            impl: DEBUG
debug: true
---
spring:
    profiles: heroku
    datasource:
        url:  jdbc:postgresql://localhost:5432/bloodmoney
        username:  bloodmoney
        password:  bloodmoneypwd
        driver-class-name:  org.postgresql.Driver
        platform: POSTGRESQL
        initialization-mode: always
    session:
        store-type: jdbc
        jdbc:
            initialize-schema: always
    jta:
        atomikos:
            connectionfactory:
                xa-connection-factory-class-name: org.postgresql.xa.PGXADataSource
    jpa:
        show-sql: true
        database-platform: POSTGRESQL
        hibernate:
            #ddl-auto: create-drop
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                temp:
                    use_jdbc_metadata_defaults: false
            #generate_statistics: true
    h2:
        console:
            enabled: false
    thymeleaf:
        cache: true
    devtools:
        livereload:
            enabled: false
        add-properties: false
    application:
        admin:
            enabled: false
server:
    compression:
        enabled: true
logging:
    level:
        root: WARN
        org:
            springframework: WARN
            hibernate.SQL: INFO
            ch:
                qos: WARN
            postgresql: DEBUG
            woehlke:
                bloodmoney:
                    config: DEBUG
                    frontend:
                        api: DEBUG
                        config: DEBUG
                        controller: DEBUG
                        model: DEBUG
                    oodm:
                        entities: DEBUG
                        repositories: DEBUG
                        services:
                            impl: DEBUG
                    user:
                        config: DEBUG
                        controller: DEBUG
                        model: DEBUG
                        services:
                            impl: DEBUG
debug: false
