endpoints:
    endpoints:
        shutdown:
            enabled: false
server:
    port: ${PORT}
    error:
        path: /fehler
    compression:
        enabled: true
        min-response-size: 2048
spring:
    devtools:
        livereload:
            enabled: true
    application:
        admin:
            enabled: true
    jpa:
        show-sql: true
        open-in-view: true
        generate-ddl: true
        hibernate:
            ddl-auto:  create-drop
            #ddl-auto: update
    thymeleaf:
        cache: false
    session:
        store-type: jdbc
        jdbc:
            initialize-schema: ALWAYS
            cleanup-cron: 0 * * * *simpleworklist *
            schema: classpath:/org/springframework/session/jdbc/schema-h2.sql
            table-name: SPRING_SESSION
    main:
        allow-bean-definition-overriding: true
org:
    woehlke:
        bloodmoney:
            dev-testing: ${BLOODMONEY_DEV_TESTING}
            user-config:
                userEmail: ${BLOODMONEY_USER_EMAIL}
                userPassword: ${BLOODMONEY_USER_PASSWORD}
                userFullname: ${BLOODMONEY_USER_FULLNAME}
            web-config:
                export-filename: "measurements.csv"
                export-filename-separator: ";"
                web-add-resource-handlers-static:
                    - "css/"
                    - "img/"
                    - "js/"
                    - "favicon.ico"
                web-add-resource-handlers:
                    - "webjars/"
            web-security:
                iterations: ${BLOODMONEY_USER_INTERATIONS}
                hashWidth: ${BLOODMONEY_USER_HASH_WIDTH}
                secret: ${BLOODMONEY_USER_SECRET}
                login-processing-url: "/j_spring_security_check"
                failure-forward-url: "/login?login_error=1"
                default-success-url: "/"
                login-page: "/login"
                logout-url: "/logout"
                username-parameter: "userEmail"
                password-parameter: "userPassword"
                delete-cookies: "JSESSIONID"
                invalidate-http-session: true
                ant-matchers-fully-authenticated: "/**"
                ant-matchers-permit-all:
                    - "/webjars/**"
                    - "/css/**"
                    - "/img/**"
                    - "/js/**"
                    - "/favicon.ico"
                    - "/test*/**"
                    - "/login*"
                    - "/register*"
                    - "/confirm*/**"
                    - "/resetPassword*"
                    - "/passwordResetConfirm*/**"
                    - "/error*"
                    - "/h2*"
logging:
    file:
        name: bloodmoney.log
    level:
        root: INFO
        org:
            woehlke:
                bloodmoney:
                    config: DEBUG
                    frontend:
                        api: DEBUG
                        config: DEBUG
                        controller: DEBUG
                        model: DEBUG
                    oodm:
                        entities: DEBUG
                        repositories: DEBUG
                        services:
                            impl: DEBUG
                    user:
                        config: DEBUG
                        controller: DEBUG
                        model: DEBUG
                        services:
                            impl: DEBUG
debug: true
---
spring:
    profiles: default
    datasource:
        platform: H2
        driver-class-name: org.h2.Driver
        username: sa
        password:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        #temporary data storage
        #url: jdbc:h2:file:/data/sample
        #url: jdbc:h2:file:C:/data/sample (Windows only)
    jpa:
        show-sql: true
        database-platform: H2
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                temp:
                    use_jdbc_metadata_defaults: false
                naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            #generate_statistics: true
    h2:
        console:
            enabled: true
            path: /h2
            settings:
                trace: true
                web-allow-others: true
                tcp-allow-others: true
                tcp-server: true
---
spring:
    profiles: developing
    datasource:
        url: jdbc:postgresql://localhost:5432/bloodmoney_developing
    jpa:
        hibernate:
            ddl-auto: update
            #ddl-auto: create-drop
---
spring:
    profiles: default2
    datasource:
        url:  jdbc:postgresql://localhost:5432/bloodmoney
        username:  java4postgres
        password:  java4postgrespwd
        driver-class-name:  org.postgresql.Driver
        platform: POSTGRESQL
    jpa:
        hibernate:
            ddl-auto: update
            #ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                temp:
                    use_jdbc_metadata_defaults: false
            #generate_statistics: true
server:
    compression:
        enabled: false
---
spring:
    profiles: testing
    datasource:
        url: jdbc:postgresql://localhost:5432/bloodmoney_testing
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
            #ddl-auto: create-drop
server:
    compression:
        enabled: false
logging:
    level:
        org:
            woehlke:
                bloodmoney:
                    config: DEBUG
                    frontend:
                        api: DEBUG
                        config: DEBUG
                        controller: DEBUG
                        model: DEBUG
                    oodm:
                        entities: DEBUG
                        repositories: DEBUG
                        services:
                            impl: DEBUG
                    user:
                        config: DEBUG
                        controller: DEBUG
                        model: DEBUG
                        services:
                            impl: DEBUG
---
spring:
    profiles: qa
    datasource:
        url: jdbc:postgresql://localhost:5432/bloodmoney_qa
        continue-on-error: true
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
            #ddl-auto: create-drop
server:
    compression:
        enabled: false
logging:
    level:
        org:
            woehlke:
                bloodmoney:
                    config: DEBUG
                    frontend:
                        api: DEBUG
                        config: DEBUG
                        controller: DEBUG
                        model: DEBUG
                    oodm:
                        entities: DEBUG
                        repositories: DEBUG
                        services:
                            impl: DEBUG
                    user:
                        config: DEBUG
                        controller: DEBUG
                        model: DEBUG
                        services:
                            impl: DEBUG
---
spring:
    profiles: heroku
    datasource:
        url:  jdbc:postgresql://localhost:5432/bloodmoney
        username:  java4postgres
        password:  java4postgrespwd
        driver-class-name:  org.postgresql.Driver
        platform: POSTGRESQL
        continue-on-error: true
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
            #ddl-auto: create-drop
    thymeleaf:
        cache: true
    devtools:
        livereload:
            enabled: false
        add-properties: false
    application:
        admin:
            enabled: false
server:
    compression:
        enabled: true
logging:
    level:
        org:
            woehlke:
                bloodmoney: WARN
            apache: WARN
            springframework: WARN
            thymeleaf: WARN
            hibernate: WARN
            hibernate.SQL: WARN
        ch:
            qos: WARN


