server:
  port: ${PORT}
  error:
    path: /fehler
  compression:
    enabled: true
    min-response-size: 2048
  servlet:
    context-path: "/"
  endpoints:
    shutdown:
      enabled: ${BLOODMONEY_DEV_TESTING}
spring:
  config:
    name: bloodmoney
  liquibase:
    enabled: false
  devtools:
    livereload:
      enabled: ${BLOODMONEY_DEV_TESTING}
  application:
    admin:
      enabled: ${BLOODMONEY_DEV_TESTING}
  datasource:
    url: jdbc:postgresql://${BLOODMONEY_DS_HOST}:5432/${BLOODMONEY_DS_DB}
    username: ${BLOODMONEY_DS_USR}
    password: ${BLOODMONEY_DS_PWD}
    driver-class-name: org.postgresql.Driver
  jta:
    atomikos:
      connectionfactory:
        xa-connection-factory-class-name: org.postgresql.xa.PGXADataSource
  jpa:
    open-in-view: true
    show-sql: true
    database-platform: POSTGRESQL
    hibernate:
      #ddl-auto: create-drop update
      ddl-auto: ${BLOODMONEY_HIBERNATE_DDL_AUTO}
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: true
  thymeleaf:
    cache: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: ALWAYS
      cleanup-cron: 0 * * * * *
      #schema: classpath:/org/springframework/session/jdbc/schema-h2.sql
      #table-name: SPRING_SESSION
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      platform: POSTGRESQL
      mode: ALWAYS
org:
  woehlke:
    bloodmoney:
      testDataHowManyTestData: 10
      devTesting: ${BLOODMONEY_DEV_TESTING}
      userConfig:
        userEmail: ${BLOODMONEY_USER_EMAIL}
        userPassword: ${BLOODMONEY_USER_PASSWORD}
        userFullname: ${BLOODMONEY_USER_FULLNAME}
      webConfig:
        exportFilename: "measurements.csv"
        exportFilenameSeparator: ";"
        webAddResourceHandlers:
          - "webjars/"
        webAddResourceHandlersStatic:
          - "bloodmoney/"
          - "icon/"
          - "languages/"
          - "test/"
          - "favicon.ico"
      webSecurity:
        loginProcessingUrl: "/j_spring_security_check"
        failureForwardUrl: "/login?login_error=1"
        defaultSuccessUrl: "/"
        login-page: "/login"
        logout-url: "/logout"
        delete-cookies: "JSESSIONID"
        invalidate-http-session: true
        antMatchersFullyAuthenticated: "/**"
        antMatchersPermitAll:
          - "/bloodmoney"
          - "/bloodmoney/**"
          - "/icon/**"
          - "/icon"
          - "/languages"
          - "/languages/**"
          - "/favicon.ico"
          - "/webjars/**"
          - "/webjars"
          - "/test*/**"
          - "/rest"
          - "/rest/**"
          - "/bpm"
          - "/login*"
          - "/register*"
          - "/confirm*/**"
          - "/resetPassword*"
          - "/passwordResetConfirm*/**"
          - "/error*"
          - "/fehler*"
        usernameParameter: "userEmail"
        passwordParameter: "userPassword"
        secret: ${BLOODMONEY_USER_SECRET}
        iterations: ${BLOODMONEY_USER_ITERATIONS}
        hashWidth: ${BLOODMONEY_USER_HASH_WIDTH}
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: INFO
        engine:
          internal: WARN
      ch:
        qos: WARN
      postgresql: WARN
      woehlke:
        java:
          bloodmoney: INFO
debug: false
---
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  application:
    admin:
      enabled: false
  jta:
    atomikos:
      properties:
        transaction-manager-unique-name: tx-manager-bloodmoney
    transaction-manager-id: tx-manager-bloodmoney
    log-dir: transaction-logs/tx-logs-bloodmoney
  jpa:
    hibernate:
      ddl-auto: update
server:
  compression:
    enabled: false
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: INFO
        engine:
          internal: WARN
      ch:
        qos: WARN
      postgresql: WARN
      woehlke:
        java:
          bloodmoney: INFO
debug: false
---
spring:
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/bloodmoney
  jta:
    atomikos:
      properties:
        transaction-manager-unique-name: tx-manager-bloodmoney
    transaction-manager-id: tx-manager-bloodmoney
    log-dir: transaction-logs/tx-logs-bloodmoney
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${PORT}
  compression:
    enabled: true
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: INFO
        engine:
          internal: WARN
      ch:
        qos: WARN
      postgresql: WARN
      woehlke:
        java:
          bloodmoney: INFO
debug: false
